// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again
// with `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'service/database/models/collection.dart';
import 'service/database/models/comic.dart';
import 'service/database/models/reading.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 5865021797219153294),
      name: 'Comic',
      lastPropertyId: const obx_int.IdUid(11, 7678703691467885808),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7370380486306027980),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 8408440939645502991),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7955610613131919683),
            name: 'subtitle',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 4476231916151024439),
            name: 'edition',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 7511039740142350253),
            name: 'thumb',
            type: 23,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 1510722415853727188),
            name: 'path',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 8710381894821253077),
            name: 'collectionId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(1, 4861892148618494335),
            relationTarget: 'Collection'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 7678703691467885808),
            name: 'reading',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 3441850510698419676),
      name: 'Collection',
      lastPropertyId: const obx_int.IdUid(3, 6989065762026602969),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 9061044297226216777),
            name: 'id',
            type: 6,
            flags: 129),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6098524084250984005),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6989065762026602969),
            name: 'description',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'comics', srcEntity: 'Comic', srcField: 'collection')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 4208959831050477538),
      name: 'Reading',
      lastPropertyId: const obx_int.IdUid(5, 9008878338535724410),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 5460971256017543726),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 7881367534898903158),
            name: 'comicId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(2, 9168055812902343374),
            relationTarget: 'Comic'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 3840235856389496195),
            name: 'actualPage',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 9008878338535724410),
            name: 'totalPages',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [obx.Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [obx.Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [obx.Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(3, 4208959831050477538),
      lastIndexId: const obx_int.IdUid(2, 9168055812902343374),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        3119939257715182086,
        4142938186539844987,
        1689048046462604959,
        3466599008865706465
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Comic: obx_int.EntityDefinition<Comic>(
        model: _entities[0],
        toOneRelations: (Comic object) => [object.collection],
        toManyRelations: (Comic object) => {},
        getId: (Comic object) => object.id,
        setId: (Comic object, int id) {
          object.id = id;
        },
        objectToFB: (Comic object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final subtitleOffset = fbb.writeString(object.subtitle);
          final editionOffset = fbb.writeString(object.edition);
          final thumbOffset = fbb.writeListInt8(object.thumb);
          final pathOffset = fbb.writeString(object.path);
          fbb.startTable(12);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, subtitleOffset);
          fbb.addOffset(3, editionOffset);
          fbb.addOffset(4, thumbOffset);
          fbb.addOffset(5, pathOffset);
          fbb.addInt64(8, object.collection.targetId);
          fbb.addBool(10, object.reading);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final subtitleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final thumbParam = const fb.Uint8ListReader(lazy: false)
              .vTableGet(buffer, rootOffset, 12, Uint8List(0)) as Uint8List;
          final editionParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final pathParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = Comic(
              title: titleParam,
              subtitle: subtitleParam,
              thumb: thumbParam,
              edition: editionParam,
              path: pathParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..reading =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 24, false);
          object.collection.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.collection.attach(store);
          return object;
        }),
    Collection: obx_int.EntityDefinition<Collection>(
        model: _entities[1],
        toOneRelations: (Collection object) => [],
        toManyRelations: (Collection object) => {
              obx_int.RelInfo<Comic>.toOneBacklink(
                      9, object.id, (Comic srcObject) => srcObject.collection):
                  object.comics
            },
        getId: (Collection object) => object.id,
        setId: (Collection object, int id) {
          object.id = id;
        },
        objectToFB: (Collection object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, descriptionOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, '');
          final object = Collection(
              title: titleParam, description: descriptionParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          obx_int.InternalToManyAccess.setRelInfo<Collection>(
              object.comics,
              store,
              obx_int.RelInfo<Comic>.toOneBacklink(
                  9, object.id, (Comic srcObject) => srcObject.collection));
          return object;
        }),
    Reading: obx_int.EntityDefinition<Reading>(
        model: _entities[2],
        toOneRelations: (Reading object) => [object.comic],
        toManyRelations: (Reading object) => {},
        getId: (Reading object) => object.id,
        setId: (Reading object, int id) {
          object.id = id;
        },
        objectToFB: (Reading object, fb.Builder fbb) {
          fbb.startTable(6);
          fbb.addInt64(0, object.id);
          fbb.addInt64(1, object.comic.targetId);
          fbb.addInt64(3, object.actualPage);
          fbb.addInt64(4, object.totalPages);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final actualPageParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final totalPagesParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0);
          final object = Reading(
              actualPage: actualPageParam, totalPages: totalPagesParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          object.comic.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 6, 0);
          object.comic.attach(store);
          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Comic] entity fields to define ObjectBox queries.
class Comic_ {
  /// See [Comic.id].
  static final id = obx.QueryIntegerProperty<Comic>(_entities[0].properties[0]);

  /// See [Comic.title].
  static final title =
      obx.QueryStringProperty<Comic>(_entities[0].properties[1]);

  /// See [Comic.subtitle].
  static final subtitle =
      obx.QueryStringProperty<Comic>(_entities[0].properties[2]);

  /// See [Comic.edition].
  static final edition =
      obx.QueryStringProperty<Comic>(_entities[0].properties[3]);

  /// See [Comic.thumb].
  static final thumb =
      obx.QueryByteVectorProperty<Comic>(_entities[0].properties[4]);

  /// See [Comic.path].
  static final path =
      obx.QueryStringProperty<Comic>(_entities[0].properties[5]);

  /// See [Comic.collection].
  static final collection =
      obx.QueryRelationToOne<Comic, Collection>(_entities[0].properties[6]);

  /// See [Comic.reading].
  static final reading =
      obx.QueryBooleanProperty<Comic>(_entities[0].properties[7]);
}

/// [Collection] entity fields to define ObjectBox queries.
class Collection_ {
  /// See [Collection.id].
  static final id =
      obx.QueryIntegerProperty<Collection>(_entities[1].properties[0]);

  /// See [Collection.title].
  static final title =
      obx.QueryStringProperty<Collection>(_entities[1].properties[1]);

  /// See [Collection.description].
  static final description =
      obx.QueryStringProperty<Collection>(_entities[1].properties[2]);

  /// see [Collection.comics]
  static final comics =
      obx.QueryBacklinkToMany<Comic, Collection>(Comic_.collection);
}

/// [Reading] entity fields to define ObjectBox queries.
class Reading_ {
  /// See [Reading.id].
  static final id =
      obx.QueryIntegerProperty<Reading>(_entities[2].properties[0]);

  /// See [Reading.comic].
  static final comic =
      obx.QueryRelationToOne<Reading, Comic>(_entities[2].properties[1]);

  /// See [Reading.actualPage].
  static final actualPage =
      obx.QueryIntegerProperty<Reading>(_entities[2].properties[2]);

  /// See [Reading.totalPages].
  static final totalPages =
      obx.QueryIntegerProperty<Reading>(_entities[2].properties[3]);
}
